name: Build and deploy pages

# https://stackoverflow.com/questions/58139406/only-run-job-on-specific-branch-with-github-actions
on:
  push:
    branches:
      - master

jobs:

  deplop:
    name: Build pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v15
      - run: nix build .
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./result
